import os
import uuid
import logging
from typing import List
from datetime import datetime
from sqlalchemy.orm import Session
from src.models.archive import ArchiveRecord
from src.core.config import settings

logger = logging.getLogger(__name__)

class ExportService:
    def __init__(self, db: Session):
        self.db = db
        # 确保导出目录存在
        self.export_dir = os.path.join(settings.DATA_DIR, "exports")
        os.makedirs(self.export_dir, exist_ok=True)

    def export_as_markdown(self, file_ids: List[int], title: str = None) -> str:
        """
        Export multiple files into a single Markdown file.
        Returns the relative path to the exported file (relative to DATA_DIR).
        """
        # 1. Fetch records
        records = (
            self.db.query(ArchiveRecord)
            .filter(ArchiveRecord.id.in_(file_ids))
            .all()
        )
        
        if not records:
            raise ValueError("No files found for the given IDs")

        # 2. Prepare content
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        export_title = title or f"Memex Export - {len(records)} Files"
        
        content_lines = [
            f"# {export_title}",
            f"> Generated by Memex on {timestamp}",
            f"> Source Files: {len(records)}",
            "",
            "---",
            ""
        ]

        # 3. Fuse content
        for record in records:
            # Metadata Header
            content_lines.append(f"## 📄 {record.filename}")
            content_lines.append(f"**ID**: {record.id} | **Date**: {record.created_at.strftime('%Y-%m-%d')}")
            
            meta = record.meta_data or {}
            if isinstance(meta, dict):
                tags = meta.get("tags", [])
                if tags:
                    content_lines.append(f"**Tags**: {', '.join(tags)}")
                summary = meta.get("summary")
                if summary:
                    content_lines.append(f"**Summary**: {summary}")

            content_lines.append("")
            content_lines.append("### Content")
            
            # Body
            full_text = record.full_text or "(No text content)"
            content_lines.append(full_text)
            
            # Separator
            content_lines.append("")
            content_lines.append("---")
            content_lines.append("")

        # 4. Write to file
        # Use UUID to prevent collision
        filename = f"export_{datetime.now().strftime('%Y%m%d')}_{uuid.uuid4().hex[:8]}.md"
        file_path = os.path.join(self.export_dir, filename)
        
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write("\n".join(content_lines))
            
            logger.info(f"✅ Exported {len(records)} files to {file_path}")
            
            # Return path relative to DATA_DIR/root for serving
            # Assuming standard file serving setup: /files/exports/filename
            return f"exports/{filename}"
            
        except Exception as e:
            logger.error(f"Failed to write export file: {e}")
            raise e
